name: biosensor
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - biopython==1.86
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.61.0
      - griddataformats==1.0.2
      - idna==3.11
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - mda-xdrlib==0.2.0
      - mdanalysis==2.9.0
      - mmtf-python==1.1.3
      - mrcfile==1.5.4
      - msgpack==1.1.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rdkit-pypi==2022.9.5
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /Users/matteomeister/miniconda3/envs/biosensor
